### ISSUE TITLE
The system can't find the specified route when using a dir with space on his name

### ISSUE THREAD

**Issue by DualBandWiFi** [CosmicDan-Android/MiA1LowLevelBackupRestoreTool#1]
**Version:** Latest, cloned it 30 min ago.
**Issue:** It doesn't parses correctly the folders with spaces on their name, sometimes it frozes, however probably this wasn't the case, because the first time it didn't.

It also gives "_The system can't find the specified route_" when making the partition table and the xml when finishing.

**Screenshot:** [_How i've typed the dir._](https://i.imgur.com/Rk9yfTf.png)
**Not sure if it helps:** [_dir of the folder tree.txt_](https://github.com/CosmicDan-Android/MiA1LowLevelBackupRestoreTool/files/2611956/dir.of.the.folder.tree.txt)

It should have ended with E:\Testing For Github\foo\bar\\\<files of the backup>

It made:
**-** E:\Testing
**-** E:\<directory of program>\For
**-** E:\<directory of program>\Github
**-** E:\<directory of program>\Github\foo
**-** E:\<directory of program>\Github\foo\bar

Regards,
Alan.

**Comment by cosmicdan** [comment]
Sorry but the project is EOL and no longer supported, I won't fix this. Just use the tool without spaces in the path anywhere.
